version: '3.0'
services:
  backend:
    container_name: BackEnd
    depends_on:
      - db
      - cache
    
    build: 
      dockerfile: ./images/backend/Dockerfile
      context: ./.
    ports:
      - 80:80
      - 443:443
    expose:
      - 80
      - 443
    env_file:
      - .env
    networks:
      - shared
    

  db:
    container_name: DataBase
    image: postgres:16.3-bullseye@sha256:6898a1c52df5c890232055196859712ee9ba381fb631d6ee207e9d23535f2a0d
    env_file:
      - .env
    depends_on:
      - migration
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - shared

  cache:
    image: redis:7.4-rc2-bookworm@sha256:abbdb3bb5d646f3c402f499467b9bffb3d550d498fa9ad105c0ed2799897282a
    env_file:
      - .env
    ports:
      - 1234:1234
    expose:
      - 1234

  migration:
    build:
      dockerfile: ./images/migrate/Dockerfile
      context: ./.

networks:
  shared:
    driver: bridge
